# Generated by Django 4.2.2 on 2023-07-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default=True, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
